DROP TABLE IF EXISTS wcf1_user_to_openid;
CREATE TABLE wcf1_user_to_openid (
	userID INT(10) NOT NULL DEFAULT 0,
	openID char(64) NOT NULL DEFAULT '',
	UNIQUE(userID),
	UNIQUE(openID)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
